#!/bin/sh

echo "Running ktlint before commit..."
mvn antrun:run@ktlint
status=$?

if [ "$status" = 0 ] ; then
    echo "\n.......................Kotlin Code is very good......................\n"
    exit 0
else
    echo 1>&2 "\n.......................You must fix the errors and warnings first, then excute commit command again...........\n"
    exit 1
fi