spring:
  datasource:
    primary:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://ec2-3-35-55-47.ap-northeast-2.compute.amazonaws.com:3306/test_db?useLegacyDatetimeCode=false&serverTimezone=GMT&useUnicode=true
        username: root
        password:
        idle-timeout: 60000
        connection-timeout: 5000
        validation-timeout: 3000
        max-lifetime: 18000000
        maximum-pool-size: 300
        minimum-idle: 50
    secondary:
      hikari:
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://ec2-3-35-55-47.ap-northeast-2.compute.amazonaws.com:3307/test_db?useLegacyDatetimeCode=false&serverTimezone=GMT&useUnicode=true
        username: root
        password:
        idle-timeout: 60000
        connection-timeout: 5000
        validation-timeout: 3000
        max-lifetime: 18000000
        maximum-pool-size: 300
        minimum-idle: 50

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
      org:
        hibernate:
          envers:
            audit_table_suffix: _history
            modified_flag_suffix: _changed
            store_data_at_delete: true
